#[
  Meta: Global constants, etc.
]#
const
  resp_ok                           {.used.} = "200 - OK"
  resp_created                      {.used.} = "201 - Created"
  resp_accepted                     {.used.} = "202 - Accepted"
  resp_badRequest                   {.used.} = "400 - Bad Request"
  resp_unauthorized                 {.used.} = "401 - Unauthorized"
  resp_forbidden                    {.used.} = "403 - Forbidden"
  resp_notFound                     {.used.} = "404 - Not Found"
  resp_methodNotAllowed             {.used.} = "405 - Method Not Allowed"
  resp_notAcceptable                {.used.} = "406 - Not Acceptable"
  resp_conflict                     {.used.} = "409 - Conflict"
  resp_preconditionFailed           {.used.} = "412 - Precondition Failed"
  resp_requestEntityTooLarge        {.used.} = "413 - Request Entity Too Large"
  resp_unsupportedMediaType         {.used.} = "415 - Unsupported Media Type"
  resp_requestedRangeNotStisfiable  {.used.} = "416 - Requested Range Not Satisfiable"
  resp_expectationFailed            {.used.} = "417 - Expectation Failed"
  resp_internalServerError          {.used.} = "500 - Internal Server Error"
  req_root                          {.used.} = "/"
  req_active_tasks                  {.used.} = "/_active_tasks"
  req_all_dbs                       {.used.} = "/_all_dbs"
  req_dbs_info                      {.used.} = "/_dbs_info"
  req_cluster_setup                 {.used.} = "/_cluster_setup"
  req_db_updates                    {.used.} = "/_db_updates"
  req_membership                    {.used.} = "/_membership"
  req_replicate                     {.used.} = "/_replicate"
  req_scheduler_jobs                {.used.} = "/_scheduler/jobs"
  req_scheduler_docs                {.used.} = "/_scheduler/docs"
  req_node_local                    {.used.} = "/_node/_local"
  req_node_local_stats              {.used.} = "/_node/_local/_stats"
  req_node_local_system             {.used.} = "/_node/_local/_system"
  req_node_local_restart            {.used.} = "/_node/_local/_restart"
  req_node_local_config             {.used.} = "/_node/_local/_config"
  req_node_local_config_reload      {.used.} = "/_node/_local/_config/_reload"
  req_search_analyze                {.used.} = "/_search_analyze"
  req_utils                         {.used.} = "/_utils"
  req_up                            {.used.} = "/_up"
  req_uuids                         {.used.} = "/_uuids"
  req_favicon_ico                   {.used.} = "/favicon.ico"
  req_reshard                       {.used.} = "/_reshard"
  req_session                       {.used.} = "/_session"